# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form: QtWidgets.QDialog):
        Form.setObjectName("Form")
        Form.resize(750, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.ico"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.lImage = QtWidgets.QLabel(Form)
        self.lImage.setGeometry(QtCore.QRect(210, 90, 501, 401))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.lImage.setFont(font)
        self.lImage.setStyleSheet("border: 3px solid black;")
        self.lImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lImage.setObjectName("lImage")
        self.lData = QtWidgets.QLabel(Form)
        self.lData.setGeometry(QtCore.QRect(40, 510, 671, 191))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.lData.setFont(font)
        self.lData.setStyleSheet("border: 1px solid black;")
        self.lData.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop)  # type: ignore
        self.lData.setObjectName("lData")
        self.bStart = QtWidgets.QPushButton(Form)
        self.bStart.setEnabled(False)
        self.bStart.setGeometry(QtCore.QRect(50, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.bStart.setFont(font)
        self.bStart.setObjectName("bStart")
        self.fType = QtWidgets.QFrame(Form)
        self.fType.setGeometry(QtCore.QRect(40, 120, 131, 91))
        self.fType.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fType.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fType.setObjectName("fType")
        self.rImage = QtWidgets.QRadioButton(self.fType)
        self.rImage.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.rImage.setFont(font)
        self.rImage.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rImage.setTabletTracking(False)
        self.rImage.setChecked(True)
        self.rImage.setObjectName("rImage")
        self.rVidio = QtWidgets.QRadioButton(self.fType)
        self.rVidio.setGeometry(QtCore.QRect(0, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.rVidio.setFont(font)
        self.rVidio.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rVidio.setObjectName("rVidio")
        self.rCamera = QtWidgets.QRadioButton(self.fType)
        self.rCamera.setGeometry(QtCore.QRect(0, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.rCamera.setFont(font)
        self.rCamera.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rCamera.setObjectName("rCamera")
        self.lTitle = QtWidgets.QLabel(Form)
        self.lTitle.setGeometry(QtCore.QRect(210, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        self.lTitle.setFont(font)
        self.lTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lTitle.setObjectName("lTitle")
        self.bPrepare = QtWidgets.QPushButton(Form)
        self.bPrepare.setGeometry(QtCore.QRect(50, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.bPrepare.setFont(font)
        self.bPrepare.setObjectName("bPrepare")

        self.retranslateUi(Form)
        self.lImage.customContextMenuRequested['QPoint'].connect(
            self.lImage.update)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.bStart, self.rImage)
        Form.setTabOrder(self.rImage, self.rVidio)

    def retranslateUi(self, Form: QtWidgets.QDialog):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "基于机器视觉的人脸表情识别系统设计-汪哲文毕业设计"))
        self.lImage.setText(_translate("Form", "图像框"))
        self.lData.setText(_translate("Form", "数据框"))
        self.bStart.setText(_translate("Form", "开始识别"))
        self.rImage.setText(_translate("Form", "图像识别"))
        self.rVidio.setText(_translate("Form", "视频识别"))
        self.rCamera.setText(_translate("Form", "实时识别"))
        self.lTitle.setText(_translate("Form", "人脸表情识别系统"))
        self.bPrepare.setText(_translate("Form", "模型载入"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
